var guiWidth = display_get_gui_width();
var barWidth = 200;
var barHeight = 20;
var barX = (guiWidth / 2) - (barWidth / 2);
var barY = 20;
draw_rectangle_color(barX, barY, barX + barWidth, barY + barHeight, c_black, c_black, c_black, c_black, false);
var coldPct = oPlayer.cold / oPlayer.coldMax;
draw_rectangle_color(barX, barY, barX + (barWidth * coldPct), barY + barHeight, c_blue, c_aqua, c_blue, c_aqua, false);
var labelText = string(round(oPlayer.cold)) + "/" + string(oPlayer.coldMax);
draw_set_color(c_white);
draw_set_halign(fa_center);
draw_set_valign(fa_middle);
draw_text(barX + (barWidth / 2), barY + (barHeight / 2), labelText);
draw_set_halign(fa_left);
draw_set_valign(fa_top);